# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "autocolors"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wecker"]
  s.date = "2011-09-10"
  s.description = "Inspired by solarized, and lots of work with various colorschemes and syntax highlight files, and driven by a need to have some color variety that doesn't stink. Tries to generate colorschemes with just the right contrast, variety, and coherence."
  s.email = "joseph.wecker@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".attic/colors.rb",
    ".attic/colorscheme.rb",
    ".attic/labtest.rb",
    ".attic/sw2.erb",
    ".attic/swatch.erb",
    ".attic/swatch3.erb",
    ".attic/test_swatch.rb",
    ".attic/test_swatch2.rb",
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "analysis/textmate/textmate-in-the-wild.txt",
    "analysis/vim/analyze-commonly-colored.sh",
    "analysis/vim/analyze-mappings.rb",
    "analysis/vim/common-mappings.list",
    "analysis/vim/commonly-colored.list",
    "analysis/vim/gather.sh",
    "analysis/vim/statements.list",
    "autocolors.gemspec",
    "format-samples/1/Sweyla866607.css",
    "format-samples/1/Sweyla866607.tmTheme",
    "format-samples/1/Sweyla866607.txt",
    "format-samples/1/sweyla866607.el",
    "format-samples/1/sweyla866607.vim",
    "lib/VERSION",
    "lib/autocolors.rb",
    "lib/autocolors/colors.rb",
    "lib/autocolors/colorschemes.rb",
    "lib/autocolors/mapping.udon",
    "lib/autocolors/templates/colorscheme.vim",
    "notes",
    "test/helper.rb",
    "test/swatch.erb",
    "test/test_autocolors.rb"
  ]
  s.homepage = "http://github.com/josephwecker/autocolors"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Automatically generates colorschemes (mostly for editors)."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<webster>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bluecloth>, [">= 0"])
    else
      s.add_dependency(%q<webster>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<roodi>, ["~> 2.1.0"])
      s.add_dependency(%q<bluecloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<webster>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<roodi>, ["~> 2.1.0"])
    s.add_dependency(%q<bluecloth>, [">= 0"])
  end
end

