
(defun sweyla866607 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/866607/"
  (interactive)
  (color-theme-install
   '(sweyla866607
     ((background-color . "#090004")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#B5C844"))))
     (font-lock-constant-face ((t (:foreground "#88A6D2"))))
     (font-lock-builtin-face ((t (:foreground "#7566DD"))))
     (font-lock-function-name-face ((t (:foreground "#CC7C46"))))
     (font-lock-variable-name-face ((t (:foreground "#749A77"))))
     (font-lock-keyword-face ((t (:foreground "#FFFF9D"))))
     (font-lock-string-face ((t (:foreground "#FFDE44"))))
     (font-lock-doc-string-face ((t (:foreground "#FFDE44"))))
     (font-lock-type-face ((t (:foreground "#FFBC00"))))
     )))

(provide 'sweyla866607)
